### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by chancharles92** [EspressoSystems/hyperplonk#1]
- [x] Protocol description (1 week)
- [x] Building block multivariate-poly-IOPs (2 weeks)
   - [x] Sumchecks (wrapper of Arkworks) https://github.com/EspressoSystems/hyperplonk/pull/7
   - [x] Zerochecks https://github.com/EspressoSystems/hyperplonk/issues/8
   - [x] #23
- [x] Compose hyperplonk from sum checks and zero checks 
   - [x] implement offline phase
   - [x] implement interactive phase
   - [x] implement query phase
- [ ] Constraint system + Arithmetization (2 weeks)
   - [ ] Interfaces: circuit config, gadgets, Arithmetization
   - [ ] Circuit config impl
   - [ ] Arithmetization impl
- [x] Proof system (3 weeks)
   - [x] Interfaces, structs, and transcripts
   - [x] Prover
   - [x] Verifier

- [x] Multilinear polynomial commitment scheme (2 weeks) #22 
   - Reference: vRAM: Faster verifiable RAM with program-independent preprocessing, appendix G
   - Syntax: follow arkworks/polycomm

- [x] Virtual Polynomial APIs
   - [x] #17 
   - [x] #25

backlogs
- [ ]  Building blocks (we are hard coding those blocks for better efficiency; we may want to build an abstraction in future)
   - [x] Product-checks
   - [ ] Lookup-checks
